In [1]:
import os
import pandas as pd
import numpy as np
from glob import glob
from collections import defaultdict
from itertools import product
from sklearn.model_selection import train_test_split

In [23]:
path = os.path.join(os.getcwd(), "data\\player_info\\*_player_info.csv")
file_path_list = glob(path)

data = pd.DataFrame()

for file_path in file_path_list:
    data = pd.concat([data, pd.read_csv(file_path, index_col=0, encoding="utf-8")], axis=0)

In [26]:
display(data.head(2))
display(data.tail(2))
print(f"Data count : {len(data.index)}")

,queueType,tier,rank,summonerId,puuid,leaguePoints,wins,losses,veteran,inactive,freshBlood,hotStreak
leagueId,,,,,,,,,,,,
707b8eb3-22ef-47a6-91ea-6ae8c2033eaa,RANKED_SOLO_5x5,BRONZE,IV,17JCLlJq-gnN3CImhWg0da753HMMRWpj8BoBR0cRNqToKLqV,TYY0Ma2PLrN1n21jJIGI2A2P7u0HlqnJZzjAxKlkf3W0wf...,35,32,33,False,False,False,False
eae68573-eb4f-4d20-b326-9063841f23ec,RANKED_SOLO_5x5,BRONZE,IV,5ic4_fnUZbj3qeqZ24elY9_E_jUy7_bmzlE2nsJSOJS3VDH-,YfQ8ukLjL8dtEG4Qxra13uatlBO9OgoNwFSVTCGQmDpWGY...,78,3,3,False,False,False,False

,queueType,tier,rank,summonerId,puuid,leaguePoints,wins,losses,veteran,inactive,freshBlood,hotStreak
leagueId,,,,,,,,,,,,
01474855-a817-3fad-a2cc-38ec089802c1,RANKED_SOLO_5x5,MASTER,I,2Hle9HbibDF2Lf_1KKjY4-l-I_aZnzDM9K4gLwUdRwlHuD...,ZZLFMboNl2j5MvLVYVExNF1wUdq_gbjiufO2JXKQ9Pnwey...,51,57,54,False,False,False,False
01474855-a817-3fad-a2cc-38ec089802c1,RANKED_SOLO_5x5,MASTER,I,_EydLgglnjsTRJUJvsrvOiKr64TUuaJemWrNu_9gPFl2fQI,I8aKvPrPl-iwETdz9xZcCt5nGlmVAUyz6AiOiSjjk3Ot04...,51,57,59,False,False,False,False

Data count : 2319285

In [16]:
low_tiers = ["IRON", "BRONZE", "SILVER", "GOLD", "PLATINUM", "EMERALD", "DIAMOND"]
low_divisions = ["I", "II", "III", "IV"]
high_tiers = ["MASTER", "GRANDMASTER", "CHALLENGER"]
high_divisions = ["I"]

low_tiers_divisions = list(product(*[low_tiers, low_divisions]))
high_tiers_divisions = list(product(*[high_tiers, high_divisions]))
tiers_divisions = low_tiers_divisions + high_tiers_divisions

sample_data = defaultdict(pd.DataFrame)

for tier, division in tiers_divisions:
    sample_data[tier+division] = data[(data["tier"] == tier) & (data["rank"] == division)]

In [17]:
data_reduced = defaultdict(pd.DataFrame)
for key, value in sample_data.items():
    data_reduced[key] = value.sample(frac=0.1)
    print(f"Original {key} data count : {len(sample_data[key].index)}")
    print(f"reduced {key} data count : {len(data_reduced[key].index)}")

Original IRONI data count : 79522
reduced IRONI data count : 7952
Original IRONII data count : 112051
reduced IRONII data count : 11205
Original IRONIII data count : 130666
reduced IRONIII data count : 13067
Original IRONIV data count : 122798
reduced IRONIV data count : 12280
Original BRONZEI data count : 82051
reduced BRONZEI data count : 8205
Original BRONZEII data count : 109188
reduced BRONZEII data count : 10919
Original BRONZEIII data count : 117420
reduced BRONZEIII data count : 11742
Original BRONZEIV data count : 147268
reduced BRONZEIV data count : 14727
Original SILVERI data count : 78299
reduced SILVERI data count : 7830
Original SILVERII data count : 105969
reduced SILVERII data count : 10597
Original SILVERIII data count : 115935
reduced SILVERIII data count : 11594
Original SILVERIV data count : 149720
reduced SILVERIV data count : 14972
Original GOLDI data count : 53930
reduced GOLDI data count : 5393
Original GOLDII data count : 86570
reduced GOLDII data count : 8657
Original GOLDIII data count : 105683
reduced GOLDIII data count : 10568
Original GOLDIV data count : 168219
reduced GOLDIV data count : 16822
Original PLATINUMI data count : 37455
reduced PLATINUMI data count : 3746
Original PLATINUMII data count : 57363
reduced PLATINUMII data count : 5736
Original PLATINUMIII data count : 69853
reduced PLATINUMIII data count : 6985
Original PLATINUMIV data count : 114776
reduced PLATINUMIV data count : 11478
Original EMERALDI data count : 29786
reduced EMERALDI data count : 2979
Original EMERALDII data count : 32312
reduced EMERALDII data count : 3231
Original EMERALDIII data count : 46811
reduced EMERALDIII data count : 4681
Original EMERALDIV data count : 90293
reduced EMERALDIV data count : 9029
Original DIAMONDI data count : 9880
reduced DIAMONDI data count : 988
Original DIAMONDII data count : 10037
reduced DIAMONDII data count : 1004
Original DIAMONDIII data count : 13284
reduced DIAMONDIII data count : 1328
Original DIAMONDIV data count : 31146
reduced DIAMONDIV data count : 3115
Original MASTERI data count : 10000
reduced MASTERI data count : 1000
Original GRANDMASTERI data count : 700
reduced GRANDMASTERI data count : 70
Original CHALLENGERI data count : 300
reduced CHALLENGERI data count : 30

In [18]:
data_concat = pd.DataFrame()

for df in data_reduced.values():
    data_concat = pd.concat([data_concat, df], axis=0)

In [20]:
display(data_concat.head(2))
display(data_concat.tail(2))

,leagueId,queueType,tier,rank,summonerId,puuid,leaguePoints,wins,losses,veteran,inactive,freshBlood,hotStreak
381864,1a5b42a4-0dc4-43f7-88df-0beb9aa1a624,RANKED_SOLO_5x5,IRON,I,tZnJSWe4Wae2Otqx85Y1-PLY2F81VmQv7JEHcy3d20x9gc...,oaJFC9thCqhRY3yCWwMoMg5uSdc0b0ySvKA3tt0cSS5HdS...,44,7,9,False,False,False,False
379033,9a7ce98a-df12-4351-9d45-7f32cdc5b6c5,RANKED_SOLO_5x5,IRON,I,GIBc1usYzfDu_EzuiQe6hcQt02j4y6K3VgIlTmSGSfY0LnY,9s1chWLt67cWRvJwQSzfHgER9tEYFKV-xtpo2_w-tGrsn7...,85,3,3,False,False,False,False

,leagueId,queueType,tier,rank,summonerId,puuid,leaguePoints,wins,losses,veteran,inactive,freshBlood,hotStreak
445191,9a7d2b6b-dbca-381f-af5a-eedaa4ff3e49,RANKED_SOLO_5x5,CHALLENGER,I,3N_s2wjgi6kO-xSComHgKnx09VoHN4XbR-JzYm3uvFLJDhM,ggWAjdLauUAspe8NBQSZo64hU98omxD8pouFYWmsrWDn6q...,1154,122,90,False,False,False,False
445144,9a7d2b6b-dbca-381f-af5a-eedaa4ff3e49,RANKED_SOLO_5x5,CHALLENGER,I,LtrRXMdZ2LZUlJ3-TSOX8XfFFAubWz_l6w1txo2yZUBDxP...,8AmEJbSrullbcB8ATHufCFJd7c1CbbHKnMx8uPAa9iKgfD...,1218,323,284,False,False,False,True

In [ ]:
# for tier in data_concat["tier"].unique():
#     tier_data = data_concat[data_concat["tier"] == tier]
#     tier_data.to_csv(f"data/reduction_data/{tier}.csv", index=False, encoding="utf-8")